### ISSUE TITLE
include_path error

### ISSUE THREAD

**Issue by burgerwhore** [backdrop-contrib/editableviews#1]
Creating an editable view. Tried a few times but keep getting the error below.  BackdrdopCMS 1.16.2 
Any ideas?
Thanks..

 Warning: include_once(modules/editablefieldseditableviews.fields.inc): failed to open stream: No such file or directory in include_once() (line 77 of /var/www/html/backdrop/modules/editableviews/editableviews.module).
    Warning: include_once(): Failed opening 'modules/editablefieldseditableviews.fields.inc' for inclusion (include_path='.:/usr/share/php') in include_once() (line 77 of /var/www/html/backdrop/modules/editableviews/editableviews.module).
    Error: Call to undefined function editableviews_field_invoke_field() in editableviews_handler_field_field_edit->edit_form() (line 159 of /var/www/html/backdrop/modules/editableviews/handlers/editableviews_handler_field_field_edit.inc).

Call to undefined function editableviews_field_invoke_field()

**Comment by laryn** [comment]
@burgerwhore It's not entirely clear to me why I wasn't getting an error on my local sandbox, but it looks like I made a gaffe while converting a portion of this from `ctools`. Can you try the latest `1.x-1.x` or this commit?
https://github.com/backdrop-contrib/editableviews/commit/3efbf88ea4b3c323d7f0a5eb846d00f8dcb61ad2

**Comment by burgerwhore** [comment]
Just downloaded and appears to be working great now. Thanks for the quick response and solution. Really awesome.
one question is there a setting to have it only save changes/diffs? Right now it looks like every content in the table gets saved even if changes were made to only one. So last updated date gets updated on content that wasn't changed.

**Comment by laryn** [comment]
Great, closing this issue but have opened another for your next question, @burgerwhore. If you're able to take the "needs work" patch from the linked D7 queue issue and try something for this module I'd be happy to review -- otherwise let's keep that issue open and I or someone will get to it at some point.
